In [142]:
import pickle
import numpy as np
import torch
# import torchtext.vocab as vocab
from torchtext.vocab import build_vocab_from_iterator

In [143]:
with open("y_test.pkl",'rb') as file1:
    y_test_pkl = pickle.load(file1)
with open("y_train.pkl",'rb') as file2:
    y_train_pkl = pickle.load(file2)

In [144]:
sent = "<SOS> hello i am a person named nikhil <EOS>"
words = sent.split()
vocab = build_vocab_from_iterator([words])
indices = [vocab[word] for word in words]
tensor = torch.tensor(indices)
tensor,indices

1lines [00:00, 8701.88lines/s]


(tensor([ 3,  6,  7,  5,  4, 10,  8,  9,  2]), [3, 6, 7, 5, 4, 10, 8, 9, 2])

In [145]:
vocab["<SOS>"]

3

In [146]:
y_train_pkl.shape

(46294,)

In [147]:
all_words = [word for sentence in y_train_pkl for word in sentence.split()]+["<EOS>","<SOS>"]
vocab = build_vocab_from_iterator([all_words])

1lines [00:00,  9.75lines/s]


In [148]:
vocab["yo"],vocab["hella"],vocab["hey"],vocab["disappointing"],vocab["the"],vocab.stoi["<pad>"]

(22210, 100434, 11428, 14541, 3, 1)

In [149]:
vocab.itos[0],vocab.itos[1],vocab.itos[2],vocab.itos[3],vocab.itos[12],vocab.itos[6200],vocab.itos[64046],vocab.itos[118767]

('<unk>',
 '<pad>',
 '<hyperlink>',
 'the',
 'is',
 'Valley',
 '<EOS>',
 '\U000e0074\U000e007f#FIFAWWC')

In [150]:
"Size of vocab: ", len(vocab)

('Size of vocab: ', 118768)

In [151]:
y_train_arr = []
for sentence in y_train_pkl:
    sent = "<SOS> " + sentence + " <EOS>"
    words = sent.split()
    indices = [vocab[word] for word in words]
    indices = indices + [1]*(65-len(indices))
    tensor = torch.tensor(indices)
    y_train_arr.append(tensor)

y_train_arr[0].shape,y_train_arr[0],max(y_train_arr, key=lambda x: len(x)).shape

(torch.Size([65]),
 tensor([64047,     6,     6,     6,     6,     6,  2195,     3, 21020,  4812,
            11,     3,   843,     5,    40,  2701,   106,  1040,  1333,  5000,
          5326,     2, 64046,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1,     1,     1,     1,     1,     1,
             1,     1,     1,     1,     1]),
 torch.Size([65]))

In [152]:
y_train = torch.stack(y_train_arr)

In [153]:
torch.save(y_train,"y_train.pt")

## y_test

In [155]:
y_test_arr = []
for sentence in y_test_pkl:
    sent = "<SOS> " + sentence + " <EOS>"
    words = sent.split()
    indices = [vocab[word] for word in words]
    indices = indices + [1]*(65-len(indices))
    tensor = torch.tensor(indices)
    y_test_arr.append(tensor)

y_test_arr[0].shape,y_test_arr[0],max(y_test_arr, key=lambda x: len(x)).shape

(torch.Size([65]),
 tensor([ 64047,     49,     19,   2781,      4,    779,      3,   8588,      8,
              6,     28,  33738,      8,      3,   9865,     16,      6,     28,
              8,   3437,    216,    252,   2810,   5740,  11026,     37, 112806,
              7,     30,   4602,    706,     16,      0,    922,     17,      0,
              0,      5,    251,     13,      0,    117,     27,    246,      2,
              2,  64046,      1,      1,      1,      1,      1,      1,      1,
              1,      1,      1,      1,      1,      1,      1,      1,      1,
              1,      1]),
 torch.Size([65]))

In [156]:
y_test = torch.stack(y_test_arr)

In [158]:
torch.save(y_test,"y_test.pt")