In [49]:
import pandas as pd
import numpy as np

In [50]:
with open("final_bad_ids.txt",'r') as badids:
    lines = badids.readlines()
    line=lines[0]
    arr = line.split(', ')
    arr[0] = arr[0][1:]
    arr[-1] = arr[-1][:-1]
    bad_ids = [int(s) for s in arr]
    # print(bad_ids)

In [3]:
df = pd.read_excel("behaviour_simulation_train.xlsx")
df.head()

id                 date  likes  \
0   1  2020-12-12 00:47:00      1   
1   2  2018-06-30 10:04:20   2750   
2   3  2020-09-29 19:47:28     57   
3   4  2020-10-01 11:40:09    152   
4   5  2018-10-19 14:30:46     41   

                                             content        username  \
0  Spend your weekend morning with a Ham, Egg, an...    TimHortonsPH   
1  Watch rapper <mention> freestyle for over an H...       IndyMusic   
2  Canadian Armenian community demands ban on mil...       CBCCanada   
3  1st in Europe to be devastated by COVID-19, It...  MKWilliamsRome   
4  Congratulations to Pauletha Butts of <mention>...           BGISD   

                                               media inferred company  
0  [Photo(previewUrl='https://pbs.twimg.com/media...      tim hortons  
1  [Photo(previewUrl='https://pbs.twimg.com/media...      independent  
2  [Photo(previewUrl='https://pbs.twimg.com/media...              cbc  
3  [Photo(previewUrl='https://pbs.twimg.com/media...         williams  
4  [Photo(previewUrl='https://pbs.twimg.com/media...      independent

In [51]:
df.head()

id                 date  likes  \
0   1  2020-12-12 00:47:00      1   
1   2  2018-06-30 10:04:20   2750   
2   3  2020-09-29 19:47:28     57   
3   4  2020-10-01 11:40:09    152   
4   5  2018-10-19 14:30:46     41   

                                             content        username  \
0  Spend your weekend morning with a Ham, Egg, an...    TimHortonsPH   
1  Watch rapper <mention> freestyle for over an H...       IndyMusic   
2  Canadian Armenian community demands ban on mil...       CBCCanada   
3  1st in Europe to be devastated by COVID-19, It...  MKWilliamsRome   
4  Congratulations to Pauletha Butts of <mention>...           BGISD   

                                               media inferred company  \
0  [Photo(previewUrl='https://pbs.twimg.com/media...      tim hortons   
1  [Photo(previewUrl='https://pbs.twimg.com/media...      independent   
2  [Photo(previewUrl='https://pbs.twimg.com/media...              cbc   
3  [Photo(previewUrl='https://pbs.twimg.com/media...         williams   
4  [Photo(previewUrl='https://pbs.twimg.com/media...      independent   

   group_id  
0    198525  
1    241838  
2     63155  
3     20887  
4     70568

In [52]:
df['group_id'] = df.groupby('content').ngroup() + 1

In [53]:
df.head()

id                 date  likes  \
0   1  2020-12-12 00:47:00      1   
1   2  2018-06-30 10:04:20   2750   
2   3  2020-09-29 19:47:28     57   
3   4  2020-10-01 11:40:09    152   
4   5  2018-10-19 14:30:46     41   

                                             content        username  \
0  Spend your weekend morning with a Ham, Egg, an...    TimHortonsPH   
1  Watch rapper <mention> freestyle for over an H...       IndyMusic   
2  Canadian Armenian community demands ban on mil...       CBCCanada   
3  1st in Europe to be devastated by COVID-19, It...  MKWilliamsRome   
4  Congratulations to Pauletha Butts of <mention>...           BGISD   

                                               media inferred company  \
0  [Photo(previewUrl='https://pbs.twimg.com/media...      tim hortons   
1  [Photo(previewUrl='https://pbs.twimg.com/media...      independent   
2  [Photo(previewUrl='https://pbs.twimg.com/media...              cbc   
3  [Photo(previewUrl='https://pbs.twimg.com/media...         williams   
4  [Photo(previewUrl='https://pbs.twimg.com/media...      independent   

   group_id  
0    198525  
1    241838  
2     63155  
3     20887  
4     70568

In [54]:
len(df['group_id'].unique())

278522

In [55]:
groups = df['group_id'].unique()
groups,len(groups)

(array([198525, 241838,  63155, ..., 139060, 213207, 122438]), 278522)

In [56]:
import numpy as np
from sklearn.model_selection import train_test_split

train_groups, temp_data = train_test_split(groups, test_size=0.3, random_state=42)

val_groups, test_groups = train_test_split(temp_data, test_size=2/3, random_state=42)

# Print the lengths of the resulting sets
print("Train set length:", len(train_groups))
print("Validation set length:", len(val_groups))
print("Test set length:", len(test_groups))

Train set length: 194965
Validation set length: 27852
Test set length: 55705


In [57]:
train_groups[:5],test_groups[:5],val_groups[:5]

(array([ 28010,  87923,  31469, 270394, 156800]),
 array([ 62372, 152999, 185760,  26250,  34409]),
 array([ 82451, 105652, 162735, 164522, 261639]))

In [58]:
41427 in test_groups,41427 in train_groups,41427 in val_groups

(False, True, False)

In [45]:
train_ids,val_ids,test_ids=[],[],[]
for i in range(len(df['group_id'])):
    # if(i%1000==5):
    #     print(df['group_id'][i])
    if df['group_id'][i] in train_groups:
        if(df['id'][i] not in bad_ids):
            train_ids.append(df['id'][i])
    
    if df['group_id'][i] in val_groups:
        if(df['id'][i] not in bad_ids):
            val_ids.append(df['id'][i])

    if df['group_id'][i] in test_groups:
        if(df['id'][i] not in bad_ids):    
            test_ids.append(df['id'][i])

In [46]:
with open('train.txt','w') as train1:
    train1.write(str(train_ids))

with open('valn.txt','w') as val1:
    val1.write(str(val_ids))

with open('test.txt','w') as test1:
    test1.write(str(test_ids))